[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#ec4899"
backgroundColor = "#030712"
secondaryBackgroundColor = "#0f172a"
textColor = "#f8fafc"
font = "sans serif"
